### ISSUE TITLE
Pose estimation window

### ISSUE THREAD

**Issue by tomrichardson** [formicidae-tracker/studio#103]
In the pose estimation, the tails of bees are often clipped. 
Can the thumbnail be slightly larger to avoid this..?

**Comment by atuleu** [comment]
Unfortunately not, as it is set at the acquisition.

>
These are bot fullframe, like the previous system, as they often take too
much time to output, and takes too much disk space. These are actual
individual files. You can check them in ants/ directory

It is the responsability of the person setting up the tracking to check
that the roi (region of interest ) is big enough to see the whole
individuals on each of those close up. It is sure it is more adapted to
ants, because if you set it right for the queen, you are good for all of
the individuals.

For one of the colonies you are working on, I saw this problem on less than
ten individuals, not ideal, but still manageable... Adding 50-100 pixel for
the next tracking experiment may solve this issues.

**Comment by tomrichardson** [comment]
OK, I understand that the size must be set correctly when the tracking is initiated... 

But if it has not been set correctly, and say the user only has a few images for a given bee, and in those the bee is clipped, then if the user starts measuring the pose by clicking on an point in the grey border outside the picture (where the tip of the abdomen should be), does the software record the pose from that point, or what..?

**Comment by tomrichardson** [comment]
Like this - see the blue is outside the image... Does the program still function when the measurements are begin/end outside the edge of the image..?
![Out](https://user-images.githubusercontent.com/1412908/84404853-44f2e280-abff-11ea-80ee-752b86cdd3e5.png)

**Comment by atuleu** [comment]
Normally I would say yes, there is no cliping of the coordinates... To be sure, save the project, and reopen it. If the tail handle is still outside, for sure there are no issues and the offset from the origin is saved. Then for the pose estimation, everything is translated to the tag reference frame...
