### ISSUE TITLE
Add tag number count next to tag in Identification panel

### ISSUE THREAD

**Issue by tomrichardson** [formicidae-tracker/studio#105]
In the pose estimation screen ('Identification'), would it be possible to add a column next to 'Nb_Measurements' indicating the number of observations of that tag..?

A user might not wish to add an orientation if he/she suspects that the tag is a false positive, which might be indicated when there is only one thumbnail for a tag and;
- The tag is partially occluded or
- The tag is at a steep angle.

Information about the number of observations for a given tag would allow the user to decide whether  the tag is suspect, and therefore whether they want to add an orientation for that tag. 
![Clipped_singleton_tags](https://user-images.githubusercontent.com/1412908/84408854-8fc32900-ac04-11ea-8726-e4c5ae0cdebd.png)

**Comment by atuleu** [comment]
I am not sure if we should add this feature. As you say, false positive detection is easy... Since close up are taken every two hours, a small closeup number is often related to a false positive. I could easily summarize the number of close up next to a tag in the tree view.

Now..  detecting partially ocluded tag is hard. Detecting false positive is even harder... That is something that you should do manually. Even the "squareness" estimation feature I wrote is buggy, and I am really happy to just have made a warning and not hide these close up from the user. Btw skewed tag are indeed detected and reported as non square. See the image below

Adding the number count is possible but I would advice not. This is not an easy number to get. It is why in the API it is a query and not just a method from the Experiment class... We have to perform quite some I/ O (I mean read a few gigabyte of file ) to get that information. We have seen in the past how it is like to do that action on a computer whithout asking the user to do trigger it manually. It feels outrageously klunky. So now if we display this information, we ask the user to load manually two thing : the close up and the statistics. And when he will not see the tag number he will ask himself why it disappear, because it won't be clear what he need to do to get full information...  Zhere are already other issue feeling that buttons to load thing are missing in a lot of places, and I am already fighting to keep most of screen space for the display of tag...

And I will not go back to lazily load anything under the hood, we saw already how it goes when you do not use a SSD...


What do you think about just asking the user to use their brain,  and detect themselve false positive (one or two closeup against 12 per day for others), badly oriented individuals at the time of capture, individuals at the edge of the screen and take the decision themselves ?

**Comment by tomrichardson** [comment]
I am happy to manually identify the few tags that are false positives, or mix-ups... Just thought that any  hints about which tags are suspicious will save users hours of time tracking down which ants die & when.

**Comment by atuleu** [comment]
I think that I do not want to change the ant selector view. But I agree the identification view should be changed to help with these informations.

**Comment by atuleu** [comment]
It is now done in the Identification workspace
