### ISSUE TITLE
Visualisation widget hotkeys

### ISSUE THREAD

**Issue by AdrianoWanderlingh** [formicidae-tracker/studio#67]
Request for visualisation widget hotkeys: start/stop the video, scroll frame by frame (back and forth), go to specific timestamp.

**Comment by atuleu** [comment]
So it is not just hotkey but a lot of functionalities to be added:
* start:/stop the video: It is indeed just a shortcut. But we need to decide what shortcut. Taking inspiration of the common one in other software:
  * click on the video frame: Easy to be done
  * space bar to toggle play/pause: Harder. Adding this shortcut may disable the spacebar everywhere in the main window, and unlike other player, we edit text in a lot of places in this interface
* Frame by Frame Scrolling: The functionnality still need to be implemented, but we could use something like youtube navigation hotkeys:
  * j/l : skip ten seconds backward/forward. Also bound to the skip keys in the controller
  * ,/.: while paused, skip one frame backward/ forward
* Go to specific timestamp: Completely new feature to be implemented here. Not sure it would be completely useful. Also, because we cannot jump randomly in a tracking data file, it means that we need to fully load them in memory to do that. So it means that it will only work within a movie segment.

Other feature that needs to be implemented:
 * Jump to next/previous frame where selected ant have been detected. Bound to the skip keys in the controller. At first they would only work in the current movie segment. ( It could be hard to be implemented across movie segment, because backward scrolling in the tracking data file is not possible, and the whole file has to be read and decoded). But at least in the movie.

@AdrianoWanderlingh @nathaliestroeymeyt : please comment

**Comment by AdrianoWanderlingh** [comment]
>     * start:/stop the video: It is indeed just a shortcut. But we need to decide what shortcut. Taking inspiration of the common one in other software:
>       
>       * click on the video frame: Easy to be done
>       * space bar to toggle play/pause: Harder. Adding this shortcut may disable the spacebar everywhere in the main window, and unlike other player, we edit text in a lot of places in this interface
> 
If it is easier, better to just go for a click on the video frame
>     * Frame by Frame Scrolling: The functionality still need to be implemented, but we could use something like youtube navigation hotkeys:
>       
>       * j/l : skip ten seconds backward/forward. Also bound to the skip keys in the controller
>       * ,/.: while paused, skip one frame backward/ forward
both useful. Skip keys are apparently not currently working.
>     * Go to specific timestamp: Completely new feature to be implemented here. Not sure it would be completely useful. Also, because we cannot jump randomly in a tracking data file, it means that we need to fully load them in memory to do that. So it means that it will only work within a movie segment.
> 
to me it could be useful to determine start/end points during annotation but is not fundamental as it can be achieved by scrolling + frame skipping. I don't know if @nathaliestroeymeyt  would consider the function useful for any reason.
> 
> Other feature that needs to be implemented:
> 
>     * Jump to next/previous frame where selected ant have been detected. Bound to the skip keys in the controller. At first they would only work in the current movie segment. ( It could be hard to be implemented across movie segment, because backward scrolling in the tracking data file is not possible, and the whole file has to be read and decoded). But at least in the movie.
> 
This feature would be useful as well, and the limitation of it working within the same movie is probably negligible.

Sorry if my initial request was not formulated in the correct way.

**Comment by atuleu** [comment]
Done in version 0.2.1
